### ISSUE TITLE
Basic example doesnt account for plugin registration in Nornir 3.3

### ISSUE THREAD

**Issue by protonjhow** [carlmontanari/nornir_ansible#135]
When following the basic example in the README.md, when you call InitNornir() you get the dreaded "Plugin not registered". 

The nornir docs on this registration are a little vague so I think it would be helpful to update the example in the readme to include the correct syntax for 3.3

I am trying to figure it out now, so if I get to that before you do, i'll push a PR.

Thanks!

**Comment by protonjhow** [comment]
```yaml
---
inventory:
    plugin: nornir.plugins.inventory.ansible.AnsibleInventory
    options:
        hostsfile: "inventory"
```

But the basic example says "AnsibleInventory" without the path.

Ill make the suggestion to Kirk to update the blog.

Apologies for the confusion
