### ISSUE TITLE
Objects are only assigned one parent.

### ISSUE THREAD

**Issue by ClausHolbechArista** [carlmontanari/nornir_ansible#141]
When running with a nested Ansible inventory like:
```yaml
all:
  children:
    DC_FABRICS:
      children:
        DC1:
          children:
            SPINES_DC1:
              hosts:
                s1-spine1:
                  ansible_host: 192.168.0.10
                s1-spine2:
                  ansible_host: 192.168.0.11
```
I would expect `s1-spine1` to be a member of `all`, `DC_FABRICS`, `DC1` and `SPINES_DC1`, and this would be very useful for filtering inside nornir.
Unfortunately the inventory plugin only relays the immediate parent, so in this case `SPINES_DC1`.

Example:
```
>>> import nornir
>>> nr = nornir.InitNornir(config_file="config.yml")
>>> nr.inventory.hosts["s1-spine1"].groups
[Group: SPINES_DC1]
>>> 
```

I would like to ask if this could be implemented without breaking existing behavior? Maybe with a knob to `set_all_parents`.

If you like, I can provide a pull request, but I wanted to hear your opinion first.

Thank you for a great plugin.
